project:
  type: book

book:
  title: "Kunnskapsbase baserte språkmodeller"
  description: "Introduksjon til utvikling av kunnskapsbase baserte språkmodeller for NAV"
  status: "Under arbeid"
  author:
    - name: Jørgen Nordmoen
      affiliation: NAV IT
      email: jorgen.halvorsen.nordmoen@nav.no
  publisher: "NAV - Arbeids- og velferdsetaten"
  image: "./assets/images/rag_overview.png"
  genre: "Guide/Tutorial/Veiledning"
  license: "CC BY"
  language: "no"
  date: now
  date-format: "DD.MM.YYYY"
  page-navigation: true
  repo-url: https://github.com/navikt
  repo-actions: [edit, issue]
  twitter-card: true
  open-graph: true
  chapters:
    - index.qmd
    - bakgrunn.qmd
    - forberedelser.qmd
    - kunnskapsbasen.qmd
    - modell.qmd
  appendices:
    - kost.qmd
    - definisjoner.qmd
  navbar:
    logo: "assets/nav_logo.svg"
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    right:
      - icon: slack
        href: https://nav-it.slack.com
        aria-label: Slack kanal for kontakt
      - icon: people-fill
        href: https://teamkatalogen.nav.no
        aria-label: Ansvarlig team hos NAV

format:
  html:
    date-modified: now
    date-format: "DD.MM.YYYY"
    lang: no
    theme:
      light: flatly
      dark: darkly
