project:
  type: book

book:
  title: "Kunnskapsbase basert språkmodeller"
  description: "Introduksjon til kunnskapsbase baserte språkmodeller på Azure for NAV"
  status: "Under arbeid"
  author: "Jørgen Nordmoen"
  date: now
  chapters:
    - index.qmd
    - bakgrunn.qmd
  navbar:
    logo: "assets/nav_logo.svg"
    logo-alt: "NAV"
    right:
      - icon: github
        href: https://github.com/navikt
        aria-label: GitHub
      - icon: slack
        href: https://nav-it.slack.com
        aria-label: Slack

format:
  html:
    theme:
      light: flatly
      dark: darkly
