project:
  type: book

book:
  title: "Kunnskapsbase baserte språkmodeller"
  description: "Introduksjon til utvikling av kunnskapsbase baserte språkmodeller for NAV"
  status: "Under arbeid"
  author:
    - name: Jørgen Nordmoen
      affiliation: NAV IT
      email: jorgen.halvorsen.nordmoen@nav.no
    - name: Beate Sildnes
      affiliation: NAV IT
      email: beate.sildnes@nav.no
  publisher: "NAV - Arbeids- og velferdsetaten"
  image: "./assets/cover.png"
  genre: "Guide, Tutorial, Veiledning"
  license: "CC BY"
  language: "no"
  date: "05.22.2024"
  date-format: "DD.MM.YYYY"
  page-navigation: true
  repo-url: https://github.com/navikt/kbs-guide
  repo-actions: [edit, issue]
  twitter-card: true
  open-graph: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - bakgrunn.qmd
    - tilbyder.qmd
    - forberedelser.qmd
    - part: kunnskapsbasen/intro.qmd
      chapters:
        - kunnskapsbasen/nks.qmd
        - kunnskapsbasen/vektordatabase.qmd
        - kunnskapsbasen/tips.qmd
    - modell.qmd
    - fremtid.qmd
  appendices:
    - appendices/kost.qmd
    - appendices/arkitektur.qmd
    - appendices/pgvector.qmd
    - appendices/definisjoner.qmd
  navbar:
    logo: "./assets/nav_logo.svg"
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    right:
      - icon: slack
        href: https://nav-it.slack.com/archives/C04MRJ9SHM4
        aria-label: Slack kanal for kontakt
      - icon: people-fill
        href: https://teamkatalog.nav.no/team/415e12bc-61fb-4579-840a-c9307765f2fc
        aria-label: Ansvarlig team hos NAV

format:
  html:
    date-modified: now
    date-format: "DD.MM.YYYY"
    lang: no
    theme:
      light: flatly
      dark: darkly
  epub:
    cover-image: ./assets/cover.png
    epub-cover-image: ./assets/cover.png
  pdf:
    toc: true
    colorlinks: true
    number-sections: true
