project:
  type: book

book:
  title: "Kunnskapsbase baserte språkmodeller"
  description: "Introduksjon til kunnskapsbase baserte språkmodeller på Azure"
  status: "Under arbeid"
  author: "Jørgen Nordmoen"
  date: now
  date-format: "DD.MM.YYYY"
  page-navigation: true
  repo-url: https://github.com/navikt
  repo-actions: [issue]
  chapters:
    - index.qmd
    - bakgrunn.qmd
  navbar:
    logo: "assets/nav_logo.svg"
    logo-alt: "NAV"
    right:
      - icon: slack
        href: https://nav-it.slack.com
        aria-label: Slack

format:
  html:
    license: "CC BY"
    theme:
      light: flatly
      dark: darkly
