# Veien videre {.sec-videre}

Når systemet er oppe og kjører er det naturlig å begynne å tenke på forbedringer
og utvidelser. Akkurat hvilke utvidelser man ønsker vil være avhengig av domenet
og teamet rundt.

## Nyttige lenker

- [NORA.llm modeller på Hugging Face](https://huggingface.co/norallm)
    - Store språkmodeller trent på norsk språk.
    - Vurder disse for kjøring lokalt.
- [`LangChain` RAG from
Scratch](https://github.com/langchain-ai/rag-from-scratch)
    - Gir en oversikt over mulige forbedringer og forslag til hvordan forbedre
    *KBS* systemet.
- [`LangGraph` dokumentasjon](https://langchain-ai.github.io/langgraph/)
    - Både dokumentasjon og "how-to-guides" til inspirasjon
- [Ragas](https://docs.ragas.io/en/stable/index.html)
    - Rammeverk for å evaluere *KBS* systemet.
- [Eksempel på hybridsøk med PostgreSQL](https://github.com/pgvector/pgvector-python/blob/master/examples/hybrid_search_rrf.py)
    - Hvordan kombinere vektorsøk med tekstsøk gjennom Reciprocal Rank Fusion.

## Forskningsartikler

- [RAFT: Adapting Language Model to Domain Specific
RAG](https://techcommunity.microsoft.com/t5/ai-ai-platform-blog/raft-a-new-way-to-teach-llms-to-be-better-at-rag/ba-p/4084674)
    - Beskriver hvordan man kan forbedre *KBS* ved å fintune en enklere modell
    på kunnskapsbasen.
    - Fordelen er at man kan bruke en enklere modell enn GPT-4, som vil være
    både billigere og raskere til å svare.
    - Burde vurderes i sammenheng med lokale modeller.
