# Om veiledningen {.unnumbered}

Denne veiledningen tar for seg hvordan komme i gang med Kunnskapsbase Baserte
Språkmodeller (Retrieval-Augmented Generation (_RAG_)), forkortet _KBS_, se
[Kapittel @sec-bakgrunn] for en introduksjon til teknikken.

Bakgrunnen for denne guiden er et ønske om å lage en søkemotor eller en chatbot
basert på store språkmodeller (se @def-sprakmodell) som kan benytte en
eksisterende kunnskapsbase for å besvare spørsmål.

Nivået på guiden antar en hvis forståelse og kjennskap til store språkmodeller.
Av den grunn er det ikke sikkert at alle termer vil bli godt nok forklart. Vi
forsøker å holde en oppdatert liste med begreper og definisjoner i
@sec-definisjoner. Bruk gjerne `Foreslå endringer` knappen i menyen til høyre
hvis du har et forslag eller tips om noe som bør forklares bedre.

Guiden antar at modellen skal kjøre på interne flater hos Nav og vil være
skreddersydd for dette formålet. Forhåpentligvis kan guiden fungere som
inspirasjon for andre systemer, samt gi en innføring i konseptet _KBS_ som kan
gjenbrukes.

Veiledningen er basert på vårt arbeid med *NKS Digital Assistent*. Koden kan
sees i følgende reoper på Github:  

- [KBS-systemet]([nks_kbs_github])  
- [Vektordatabase for NKS Kunnskapsartikler]([nks_vdb_github])  
- [Vektordatabase for nav.no]([navno_vdb_github])  

Merk at vi har valgt å lenke til commits som tilsvarer det omtrentlige tidspunktet 
for når denne teksten sist ble oppdatert.

# Endringslogg

- **12.03.2025**: Utvidet med kapitler om mer avanserte KBS-teknikker
- **30.09.2024**: Modell med `LangChain` og `LangGraph`
- **{{< meta date >}}**: Første versjon publisert

[nks_kbs_github]: https://github.com/navikt/nks_kbs/tree/5e7131917fb47f5fc7345cc35badf38d72f8245a
[nks_vdb_github]: https://github.com/navikt/nks_vdb/tree/368f42bc40ce290f0cbdbd8374e042596a086624
[navno_vdb_github]: https://github.com/navikt/navno_vdb/tree/3f3bb39af1e043d7b939db1f1bd355e4bf3ff330