# Begreper og definisjoner {#sec-definisjoner}

Vi forsøker her å holde en oppdatert liste med begreper og definisjoner som kan
brukes som oppslagsverk.

---

::: {#def-azure-openai}
## Azure OpenAI Service
Er navnet på det helhetlige Generativ KI (@def-gki) produktet til Microsoft på
Azure.
:::

::: {#def-embedding}
## Embedding
En embedding er en vektor som forsøker å representere den semantiske meningen
til media som kan være tekst, bilde, video eller lyd. Vi snakker ofte om
embedding modeller som er modeller som skaper vektorene som sin output.
:::

::: {#def-kontekst}
## Kontekst
Kontekst eller kontekstvindu refererer til teksten eller inputen man gir en
Språkmodell (@def-sprakmodell) for å generere ny output. Størrelsen på
konteksten er begrenset av modellen og man kan ikke overskride den gitte
størrelsen.
:::

::: {#def-ki}
## Kunstig Intelligens (KI)
KI er fagfeltet innen datavitenskapen som utvikler metoder for å la datamaskiner
løse oppgaver på egenhånd.

> [E]n datamaskin som er i stand til å løse oppgaver uten å få instruksjoner fra
> et menneske om hvordan den skal gjøre det[.] - [SNL][snl_ki]
:::

::: {#def-gki}
## Generativ Kunstig Intelligens (GKI)
GKI er en samlebetegnelse for metoder som bruker store nevrale nettverk til å
generere media. [Språkmodeller @def-sprakmodell] er et eksempel på GKI.
:::

::: {#def-prompt}
## Prompt (eller ledetekst)
Er teksten vi gir med oppgave til språkmodellen. Den kan referere til både
systemteksten vi designer, men også spørsmålet til brukeren.
:::

::: {#def-prompt-engineer}
## Prompt engineer
Er en betegnelse på arbeidet med å designe [ledeteksten @def-prompt] til en
språkmodell.  Betegnelsen kan brukes både om det tekniske arbeidet, men kan også
brukes om måten brukere tilpasser spørsmålene sin for å oppnå ønsket output.
:::

::: {#def-sprakmodell}
## Språkmodell
I denne veiledningen brukes [språkmodell][snl_sprakmodell] og [Store
Språkmodeller][wiki_llm] om hverandre og refererer til store kunstige nevrale
nettverk som kan prosessere naturlig språk og generere naturlig språk som svar.
:::

::: {#def-temperatur}
## Temperatur
I konteksten av [Språkmodeller @def-sprakmodell] refererer temperatur til et
parameter som styrer hvor stor frihet modellen har til å, *tilfeldig*, velge
neste passende ord i svaret sitt. Høyere temperatur gir mer variasjon i svar,
mens lavere temperatur gir mer uniforme svar.
:::

::: {#def-vertex-ai}
## Vertex AI
Er navnet på det helhetlige Generativ KI (@def-gki) produktet til Google på GCP.
:::

[wiki_llm]: https://en.wikipedia.org/wiki/Large_language_model
[snl_sprakmodell]: https://snl.no/spr%C3%A5kmodell#-Nyere_spr%C3%A5kmodeller
[snl_ki]: https://snl.no/kunstig_intelligens
