name: Publiser KBS bok

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Install Quarto
              uses: quarto-dev/quarto-actions/setup@v2
              with:
                # Trenger Latex for PDF output
                tinytex: true
            - name: Render project
              uses: quarto-dev/quarto-actions/render@v2
            - name: Last opp internt
              uses: navikt/story-upload@v1
              with:
                id: 58aa330c-3a72-470e-926f-22e029719879
                dir: _book
                team_token: ${{ secrets.TEAM_TOKEN }}
                env: prod
                public: false
            - name: Last opp eksternt
              uses: navikt/story-upload@v1
              with:
                id: 7fa5a42e-b068-4320-88c2-adbafe414989
                dir: _book
                team_token: ${{ secrets.TEAM_TOKEN }}
                env: prod
                public: true
